/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.apache.fineract.client.models.GetLoanChargeCalculationType;
import org.apache.fineract.client.models.GetLoanChargeTimeType;
import org.apache.fineract.client.models.GetLoanProductsChargeAppliesTo;
import org.apache.fineract.client.models.GetLoanProductsCurrencyOptions;
import org.apache.fineract.client.models.GetLoansChargePaymentMode;
/**
 * GetLoanProductsChargeOptions
 */


public class GetLoanProductsChargeOptions {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("penalty")
  private Boolean penalty = null;

  @SerializedName("currency")
  private GetLoanProductsCurrencyOptions currency = null;

  @SerializedName("amount")
  private Long amount = null;

  @SerializedName("chargeTimeType")
  private GetLoanChargeTimeType chargeTimeType = null;

  @SerializedName("chargeAppliesTo")
  private GetLoanProductsChargeAppliesTo chargeAppliesTo = null;

  @SerializedName("chargeCalculationType")
  private GetLoanChargeCalculationType chargeCalculationType = null;

  @SerializedName("chargePaymentMode")
  private GetLoansChargePaymentMode chargePaymentMode = null;

  public GetLoanProductsChargeOptions id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "5", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetLoanProductsChargeOptions name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "des charges", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetLoanProductsChargeOptions active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(example = "true", description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public GetLoanProductsChargeOptions penalty(Boolean penalty) {
    this.penalty = penalty;
    return this;
  }

   /**
   * Get penalty
   * @return penalty
  **/
  @Schema(example = "false", description = "")
  public Boolean isPenalty() {
    return penalty;
  }

  public void setPenalty(Boolean penalty) {
    this.penalty = penalty;
  }

  public GetLoanProductsChargeOptions currency(GetLoanProductsCurrencyOptions currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public GetLoanProductsCurrencyOptions getCurrency() {
    return currency;
  }

  public void setCurrency(GetLoanProductsCurrencyOptions currency) {
    this.currency = currency;
  }

  public GetLoanProductsChargeOptions amount(Long amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(example = "100", description = "")
  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public GetLoanProductsChargeOptions chargeTimeType(GetLoanChargeTimeType chargeTimeType) {
    this.chargeTimeType = chargeTimeType;
    return this;
  }

   /**
   * Get chargeTimeType
   * @return chargeTimeType
  **/
  @Schema(description = "")
  public GetLoanChargeTimeType getChargeTimeType() {
    return chargeTimeType;
  }

  public void setChargeTimeType(GetLoanChargeTimeType chargeTimeType) {
    this.chargeTimeType = chargeTimeType;
  }

  public GetLoanProductsChargeOptions chargeAppliesTo(GetLoanProductsChargeAppliesTo chargeAppliesTo) {
    this.chargeAppliesTo = chargeAppliesTo;
    return this;
  }

   /**
   * Get chargeAppliesTo
   * @return chargeAppliesTo
  **/
  @Schema(description = "")
  public GetLoanProductsChargeAppliesTo getChargeAppliesTo() {
    return chargeAppliesTo;
  }

  public void setChargeAppliesTo(GetLoanProductsChargeAppliesTo chargeAppliesTo) {
    this.chargeAppliesTo = chargeAppliesTo;
  }

  public GetLoanProductsChargeOptions chargeCalculationType(GetLoanChargeCalculationType chargeCalculationType) {
    this.chargeCalculationType = chargeCalculationType;
    return this;
  }

   /**
   * Get chargeCalculationType
   * @return chargeCalculationType
  **/
  @Schema(description = "")
  public GetLoanChargeCalculationType getChargeCalculationType() {
    return chargeCalculationType;
  }

  public void setChargeCalculationType(GetLoanChargeCalculationType chargeCalculationType) {
    this.chargeCalculationType = chargeCalculationType;
  }

  public GetLoanProductsChargeOptions chargePaymentMode(GetLoansChargePaymentMode chargePaymentMode) {
    this.chargePaymentMode = chargePaymentMode;
    return this;
  }

   /**
   * Get chargePaymentMode
   * @return chargePaymentMode
  **/
  @Schema(description = "")
  public GetLoansChargePaymentMode getChargePaymentMode() {
    return chargePaymentMode;
  }

  public void setChargePaymentMode(GetLoansChargePaymentMode chargePaymentMode) {
    this.chargePaymentMode = chargePaymentMode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLoanProductsChargeOptions getLoanProductsChargeOptions = (GetLoanProductsChargeOptions) o;
    return Objects.equals(this.id, getLoanProductsChargeOptions.id) &&
        Objects.equals(this.name, getLoanProductsChargeOptions.name) &&
        Objects.equals(this.active, getLoanProductsChargeOptions.active) &&
        Objects.equals(this.penalty, getLoanProductsChargeOptions.penalty) &&
        Objects.equals(this.currency, getLoanProductsChargeOptions.currency) &&
        Objects.equals(this.amount, getLoanProductsChargeOptions.amount) &&
        Objects.equals(this.chargeTimeType, getLoanProductsChargeOptions.chargeTimeType) &&
        Objects.equals(this.chargeAppliesTo, getLoanProductsChargeOptions.chargeAppliesTo) &&
        Objects.equals(this.chargeCalculationType, getLoanProductsChargeOptions.chargeCalculationType) &&
        Objects.equals(this.chargePaymentMode, getLoanProductsChargeOptions.chargePaymentMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, active, penalty, currency, amount, chargeTimeType, chargeAppliesTo, chargeCalculationType, chargePaymentMode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLoanProductsChargeOptions {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    penalty: ").append(toIndentedString(penalty)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    chargeTimeType: ").append(toIndentedString(chargeTimeType)).append("\n");
    sb.append("    chargeAppliesTo: ").append(toIndentedString(chargeAppliesTo)).append("\n");
    sb.append("    chargeCalculationType: ").append(toIndentedString(chargeCalculationType)).append("\n");
    sb.append("    chargePaymentMode: ").append(toIndentedString(chargePaymentMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
