/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.apache.fineract.client.models.GetLoanProductsAssetAccountOptions;
import org.apache.fineract.client.models.GetLoanProductsExpenseAccountOptions;
import org.apache.fineract.client.models.GetLoanProductsIncomeAccountOptions;
import org.apache.fineract.client.models.GetLoanProductsLiabilityAccountOptions;
/**
 * GetLoanProductsAccountingMappingOptions
 */


public class GetLoanProductsAccountingMappingOptions {
  @SerializedName("liabilityAccountOptions")
  private List<GetLoanProductsLiabilityAccountOptions> liabilityAccountOptions = null;

  @SerializedName("assetAccountOptions")
  private List<GetLoanProductsAssetAccountOptions> assetAccountOptions = null;

  @SerializedName("expenseAccountOptions")
  private List<GetLoanProductsExpenseAccountOptions> expenseAccountOptions = null;

  @SerializedName("incomeAccountOptions")
  private List<GetLoanProductsIncomeAccountOptions> incomeAccountOptions = null;

  public GetLoanProductsAccountingMappingOptions liabilityAccountOptions(List<GetLoanProductsLiabilityAccountOptions> liabilityAccountOptions) {
    this.liabilityAccountOptions = liabilityAccountOptions;
    return this;
  }

  public GetLoanProductsAccountingMappingOptions addLiabilityAccountOptionsItem(GetLoanProductsLiabilityAccountOptions liabilityAccountOptionsItem) {
    if (this.liabilityAccountOptions == null) {
      this.liabilityAccountOptions = new ArrayList<>();
    }
    this.liabilityAccountOptions.add(liabilityAccountOptionsItem);
    return this;
  }

   /**
   * Get liabilityAccountOptions
   * @return liabilityAccountOptions
  **/
  @Schema(description = "")
  public List<GetLoanProductsLiabilityAccountOptions> getLiabilityAccountOptions() {
    return liabilityAccountOptions;
  }

  public void setLiabilityAccountOptions(List<GetLoanProductsLiabilityAccountOptions> liabilityAccountOptions) {
    this.liabilityAccountOptions = liabilityAccountOptions;
  }

  public GetLoanProductsAccountingMappingOptions assetAccountOptions(List<GetLoanProductsAssetAccountOptions> assetAccountOptions) {
    this.assetAccountOptions = assetAccountOptions;
    return this;
  }

  public GetLoanProductsAccountingMappingOptions addAssetAccountOptionsItem(GetLoanProductsAssetAccountOptions assetAccountOptionsItem) {
    if (this.assetAccountOptions == null) {
      this.assetAccountOptions = new ArrayList<>();
    }
    this.assetAccountOptions.add(assetAccountOptionsItem);
    return this;
  }

   /**
   * Get assetAccountOptions
   * @return assetAccountOptions
  **/
  @Schema(description = "")
  public List<GetLoanProductsAssetAccountOptions> getAssetAccountOptions() {
    return assetAccountOptions;
  }

  public void setAssetAccountOptions(List<GetLoanProductsAssetAccountOptions> assetAccountOptions) {
    this.assetAccountOptions = assetAccountOptions;
  }

  public GetLoanProductsAccountingMappingOptions expenseAccountOptions(List<GetLoanProductsExpenseAccountOptions> expenseAccountOptions) {
    this.expenseAccountOptions = expenseAccountOptions;
    return this;
  }

  public GetLoanProductsAccountingMappingOptions addExpenseAccountOptionsItem(GetLoanProductsExpenseAccountOptions expenseAccountOptionsItem) {
    if (this.expenseAccountOptions == null) {
      this.expenseAccountOptions = new ArrayList<>();
    }
    this.expenseAccountOptions.add(expenseAccountOptionsItem);
    return this;
  }

   /**
   * Get expenseAccountOptions
   * @return expenseAccountOptions
  **/
  @Schema(description = "")
  public List<GetLoanProductsExpenseAccountOptions> getExpenseAccountOptions() {
    return expenseAccountOptions;
  }

  public void setExpenseAccountOptions(List<GetLoanProductsExpenseAccountOptions> expenseAccountOptions) {
    this.expenseAccountOptions = expenseAccountOptions;
  }

  public GetLoanProductsAccountingMappingOptions incomeAccountOptions(List<GetLoanProductsIncomeAccountOptions> incomeAccountOptions) {
    this.incomeAccountOptions = incomeAccountOptions;
    return this;
  }

  public GetLoanProductsAccountingMappingOptions addIncomeAccountOptionsItem(GetLoanProductsIncomeAccountOptions incomeAccountOptionsItem) {
    if (this.incomeAccountOptions == null) {
      this.incomeAccountOptions = new ArrayList<>();
    }
    this.incomeAccountOptions.add(incomeAccountOptionsItem);
    return this;
  }

   /**
   * Get incomeAccountOptions
   * @return incomeAccountOptions
  **/
  @Schema(description = "")
  public List<GetLoanProductsIncomeAccountOptions> getIncomeAccountOptions() {
    return incomeAccountOptions;
  }

  public void setIncomeAccountOptions(List<GetLoanProductsIncomeAccountOptions> incomeAccountOptions) {
    this.incomeAccountOptions = incomeAccountOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLoanProductsAccountingMappingOptions getLoanProductsAccountingMappingOptions = (GetLoanProductsAccountingMappingOptions) o;
    return Objects.equals(this.liabilityAccountOptions, getLoanProductsAccountingMappingOptions.liabilityAccountOptions) &&
        Objects.equals(this.assetAccountOptions, getLoanProductsAccountingMappingOptions.assetAccountOptions) &&
        Objects.equals(this.expenseAccountOptions, getLoanProductsAccountingMappingOptions.expenseAccountOptions) &&
        Objects.equals(this.incomeAccountOptions, getLoanProductsAccountingMappingOptions.incomeAccountOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(liabilityAccountOptions, assetAccountOptions, expenseAccountOptions, incomeAccountOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLoanProductsAccountingMappingOptions {\n");
    
    sb.append("    liabilityAccountOptions: ").append(toIndentedString(liabilityAccountOptions)).append("\n");
    sb.append("    assetAccountOptions: ").append(toIndentedString(assetAccountOptions)).append("\n");
    sb.append("    expenseAccountOptions: ").append(toIndentedString(expenseAccountOptions)).append("\n");
    sb.append("    incomeAccountOptions: ").append(toIndentedString(incomeAccountOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
