/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.apache.fineract.client.models.GetChargesChargeCalculationType;
import org.apache.fineract.client.models.GetChargesChargeTimeType;
import org.apache.fineract.client.models.GetChargesCurrencyResponse;
/**
 * GetSavingsAccountsSavingsAccountIdChargesResponse
 */
@Schema(description = "GetSavingsAccountsSavingsAccountIdChargesResponse")

public class GetSavingsAccountsSavingsAccountIdChargesResponse {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("chargeId")
  private Integer chargeId = null;

  @SerializedName("accountId")
  private Integer accountId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("chargeTimeType")
  private GetChargesChargeTimeType chargeTimeType = null;

  @SerializedName("chargeCalculationType")
  private GetChargesChargeCalculationType chargeCalculationType = null;

  @SerializedName("percentage")
  private Double percentage = null;

  @SerializedName("amountPercentageAppliedTo")
  private Double amountPercentageAppliedTo = null;

  @SerializedName("currency")
  private GetChargesCurrencyResponse currency = null;

  @SerializedName("amount")
  private Float amount = null;

  @SerializedName("amountPaid")
  private Float amountPaid = null;

  @SerializedName("amountWaived")
  private Float amountWaived = null;

  @SerializedName("amountWrittenOff")
  private Float amountWrittenOff = null;

  @SerializedName("amountOutstanding")
  private Float amountOutstanding = null;

  @SerializedName("amountOrPercentage")
  private Float amountOrPercentage = null;

  @SerializedName("penalty")
  private Boolean penalty = null;

  public GetSavingsAccountsSavingsAccountIdChargesResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse chargeId(Integer chargeId) {
    this.chargeId = chargeId;
    return this;
  }

   /**
   * Get chargeId
   * @return chargeId
  **/
  @Schema(example = "3", description = "")
  public Integer getChargeId() {
    return chargeId;
  }

  public void setChargeId(Integer chargeId) {
    this.chargeId = chargeId;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @Schema(example = "57", description = "")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Savings account maintenance fee", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse chargeTimeType(GetChargesChargeTimeType chargeTimeType) {
    this.chargeTimeType = chargeTimeType;
    return this;
  }

   /**
   * Get chargeTimeType
   * @return chargeTimeType
  **/
  @Schema(description = "")
  public GetChargesChargeTimeType getChargeTimeType() {
    return chargeTimeType;
  }

  public void setChargeTimeType(GetChargesChargeTimeType chargeTimeType) {
    this.chargeTimeType = chargeTimeType;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse chargeCalculationType(GetChargesChargeCalculationType chargeCalculationType) {
    this.chargeCalculationType = chargeCalculationType;
    return this;
  }

   /**
   * Get chargeCalculationType
   * @return chargeCalculationType
  **/
  @Schema(description = "")
  public GetChargesChargeCalculationType getChargeCalculationType() {
    return chargeCalculationType;
  }

  public void setChargeCalculationType(GetChargesChargeCalculationType chargeCalculationType) {
    this.chargeCalculationType = chargeCalculationType;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse percentage(Double percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * @return percentage
  **/
  @Schema(example = "0", description = "")
  public Double getPercentage() {
    return percentage;
  }

  public void setPercentage(Double percentage) {
    this.percentage = percentage;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amountPercentageAppliedTo(Double amountPercentageAppliedTo) {
    this.amountPercentageAppliedTo = amountPercentageAppliedTo;
    return this;
  }

   /**
   * Get amountPercentageAppliedTo
   * @return amountPercentageAppliedTo
  **/
  @Schema(example = "0", description = "")
  public Double getAmountPercentageAppliedTo() {
    return amountPercentageAppliedTo;
  }

  public void setAmountPercentageAppliedTo(Double amountPercentageAppliedTo) {
    this.amountPercentageAppliedTo = amountPercentageAppliedTo;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse currency(GetChargesCurrencyResponse currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public GetChargesCurrencyResponse getCurrency() {
    return currency;
  }

  public void setCurrency(GetChargesCurrencyResponse currency) {
    this.currency = currency;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amount(Float amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(example = "100", description = "")
  public Float getAmount() {
    return amount;
  }

  public void setAmount(Float amount) {
    this.amount = amount;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amountPaid(Float amountPaid) {
    this.amountPaid = amountPaid;
    return this;
  }

   /**
   * Get amountPaid
   * @return amountPaid
  **/
  @Schema(example = "0", description = "")
  public Float getAmountPaid() {
    return amountPaid;
  }

  public void setAmountPaid(Float amountPaid) {
    this.amountPaid = amountPaid;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amountWaived(Float amountWaived) {
    this.amountWaived = amountWaived;
    return this;
  }

   /**
   * Get amountWaived
   * @return amountWaived
  **/
  @Schema(example = "0", description = "")
  public Float getAmountWaived() {
    return amountWaived;
  }

  public void setAmountWaived(Float amountWaived) {
    this.amountWaived = amountWaived;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amountWrittenOff(Float amountWrittenOff) {
    this.amountWrittenOff = amountWrittenOff;
    return this;
  }

   /**
   * Get amountWrittenOff
   * @return amountWrittenOff
  **/
  @Schema(example = "0", description = "")
  public Float getAmountWrittenOff() {
    return amountWrittenOff;
  }

  public void setAmountWrittenOff(Float amountWrittenOff) {
    this.amountWrittenOff = amountWrittenOff;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amountOutstanding(Float amountOutstanding) {
    this.amountOutstanding = amountOutstanding;
    return this;
  }

   /**
   * Get amountOutstanding
   * @return amountOutstanding
  **/
  @Schema(example = "100", description = "")
  public Float getAmountOutstanding() {
    return amountOutstanding;
  }

  public void setAmountOutstanding(Float amountOutstanding) {
    this.amountOutstanding = amountOutstanding;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse amountOrPercentage(Float amountOrPercentage) {
    this.amountOrPercentage = amountOrPercentage;
    return this;
  }

   /**
   * Get amountOrPercentage
   * @return amountOrPercentage
  **/
  @Schema(example = "100", description = "")
  public Float getAmountOrPercentage() {
    return amountOrPercentage;
  }

  public void setAmountOrPercentage(Float amountOrPercentage) {
    this.amountOrPercentage = amountOrPercentage;
  }

  public GetSavingsAccountsSavingsAccountIdChargesResponse penalty(Boolean penalty) {
    this.penalty = penalty;
    return this;
  }

   /**
   * Get penalty
   * @return penalty
  **/
  @Schema(example = "false", description = "")
  public Boolean isPenalty() {
    return penalty;
  }

  public void setPenalty(Boolean penalty) {
    this.penalty = penalty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSavingsAccountsSavingsAccountIdChargesResponse getSavingsAccountsSavingsAccountIdChargesResponse = (GetSavingsAccountsSavingsAccountIdChargesResponse) o;
    return Objects.equals(this.id, getSavingsAccountsSavingsAccountIdChargesResponse.id) &&
        Objects.equals(this.chargeId, getSavingsAccountsSavingsAccountIdChargesResponse.chargeId) &&
        Objects.equals(this.accountId, getSavingsAccountsSavingsAccountIdChargesResponse.accountId) &&
        Objects.equals(this.name, getSavingsAccountsSavingsAccountIdChargesResponse.name) &&
        Objects.equals(this.chargeTimeType, getSavingsAccountsSavingsAccountIdChargesResponse.chargeTimeType) &&
        Objects.equals(this.chargeCalculationType, getSavingsAccountsSavingsAccountIdChargesResponse.chargeCalculationType) &&
        Objects.equals(this.percentage, getSavingsAccountsSavingsAccountIdChargesResponse.percentage) &&
        Objects.equals(this.amountPercentageAppliedTo, getSavingsAccountsSavingsAccountIdChargesResponse.amountPercentageAppliedTo) &&
        Objects.equals(this.currency, getSavingsAccountsSavingsAccountIdChargesResponse.currency) &&
        Objects.equals(this.amount, getSavingsAccountsSavingsAccountIdChargesResponse.amount) &&
        Objects.equals(this.amountPaid, getSavingsAccountsSavingsAccountIdChargesResponse.amountPaid) &&
        Objects.equals(this.amountWaived, getSavingsAccountsSavingsAccountIdChargesResponse.amountWaived) &&
        Objects.equals(this.amountWrittenOff, getSavingsAccountsSavingsAccountIdChargesResponse.amountWrittenOff) &&
        Objects.equals(this.amountOutstanding, getSavingsAccountsSavingsAccountIdChargesResponse.amountOutstanding) &&
        Objects.equals(this.amountOrPercentage, getSavingsAccountsSavingsAccountIdChargesResponse.amountOrPercentage) &&
        Objects.equals(this.penalty, getSavingsAccountsSavingsAccountIdChargesResponse.penalty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, chargeId, accountId, name, chargeTimeType, chargeCalculationType, percentage, amountPercentageAppliedTo, currency, amount, amountPaid, amountWaived, amountWrittenOff, amountOutstanding, amountOrPercentage, penalty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSavingsAccountsSavingsAccountIdChargesResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    chargeId: ").append(toIndentedString(chargeId)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    chargeTimeType: ").append(toIndentedString(chargeTimeType)).append("\n");
    sb.append("    chargeCalculationType: ").append(toIndentedString(chargeCalculationType)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    amountPercentageAppliedTo: ").append(toIndentedString(amountPercentageAppliedTo)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amountPaid: ").append(toIndentedString(amountPaid)).append("\n");
    sb.append("    amountWaived: ").append(toIndentedString(amountWaived)).append("\n");
    sb.append("    amountWrittenOff: ").append(toIndentedString(amountWrittenOff)).append("\n");
    sb.append("    amountOutstanding: ").append(toIndentedString(amountOutstanding)).append("\n");
    sb.append("    amountOrPercentage: ").append(toIndentedString(amountOrPercentage)).append("\n");
    sb.append("    penalty: ").append(toIndentedString(penalty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
