/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.apache.fineract.client.models.GetSelfSavingsPaymentType;
/**
 * GetSelfSavingsPaymentDetailData
 */


public class GetSelfSavingsPaymentDetailData {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("paymentType")
  private GetSelfSavingsPaymentType paymentType = null;

  @SerializedName("accountNumber")
  private Integer accountNumber = null;

  @SerializedName("checkNumber")
  private Integer checkNumber = null;

  @SerializedName("routingCode")
  private Integer routingCode = null;

  @SerializedName("receiptNumber")
  private Integer receiptNumber = null;

  @SerializedName("bankNumber")
  private Integer bankNumber = null;

  public GetSelfSavingsPaymentDetailData id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "62", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetSelfSavingsPaymentDetailData paymentType(GetSelfSavingsPaymentType paymentType) {
    this.paymentType = paymentType;
    return this;
  }

   /**
   * Get paymentType
   * @return paymentType
  **/
  @Schema(description = "")
  public GetSelfSavingsPaymentType getPaymentType() {
    return paymentType;
  }

  public void setPaymentType(GetSelfSavingsPaymentType paymentType) {
    this.paymentType = paymentType;
  }

  public GetSelfSavingsPaymentDetailData accountNumber(Integer accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(description = "")
  public Integer getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(Integer accountNumber) {
    this.accountNumber = accountNumber;
  }

  public GetSelfSavingsPaymentDetailData checkNumber(Integer checkNumber) {
    this.checkNumber = checkNumber;
    return this;
  }

   /**
   * Get checkNumber
   * @return checkNumber
  **/
  @Schema(description = "")
  public Integer getCheckNumber() {
    return checkNumber;
  }

  public void setCheckNumber(Integer checkNumber) {
    this.checkNumber = checkNumber;
  }

  public GetSelfSavingsPaymentDetailData routingCode(Integer routingCode) {
    this.routingCode = routingCode;
    return this;
  }

   /**
   * Get routingCode
   * @return routingCode
  **/
  @Schema(description = "")
  public Integer getRoutingCode() {
    return routingCode;
  }

  public void setRoutingCode(Integer routingCode) {
    this.routingCode = routingCode;
  }

  public GetSelfSavingsPaymentDetailData receiptNumber(Integer receiptNumber) {
    this.receiptNumber = receiptNumber;
    return this;
  }

   /**
   * Get receiptNumber
   * @return receiptNumber
  **/
  @Schema(description = "")
  public Integer getReceiptNumber() {
    return receiptNumber;
  }

  public void setReceiptNumber(Integer receiptNumber) {
    this.receiptNumber = receiptNumber;
  }

  public GetSelfSavingsPaymentDetailData bankNumber(Integer bankNumber) {
    this.bankNumber = bankNumber;
    return this;
  }

   /**
   * Get bankNumber
   * @return bankNumber
  **/
  @Schema(description = "")
  public Integer getBankNumber() {
    return bankNumber;
  }

  public void setBankNumber(Integer bankNumber) {
    this.bankNumber = bankNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSelfSavingsPaymentDetailData getSelfSavingsPaymentDetailData = (GetSelfSavingsPaymentDetailData) o;
    return Objects.equals(this.id, getSelfSavingsPaymentDetailData.id) &&
        Objects.equals(this.paymentType, getSelfSavingsPaymentDetailData.paymentType) &&
        Objects.equals(this.accountNumber, getSelfSavingsPaymentDetailData.accountNumber) &&
        Objects.equals(this.checkNumber, getSelfSavingsPaymentDetailData.checkNumber) &&
        Objects.equals(this.routingCode, getSelfSavingsPaymentDetailData.routingCode) &&
        Objects.equals(this.receiptNumber, getSelfSavingsPaymentDetailData.receiptNumber) &&
        Objects.equals(this.bankNumber, getSelfSavingsPaymentDetailData.bankNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, paymentType, accountNumber, checkNumber, routingCode, receiptNumber, bankNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSelfSavingsPaymentDetailData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    checkNumber: ").append(toIndentedString(checkNumber)).append("\n");
    sb.append("    routingCode: ").append(toIndentedString(routingCode)).append("\n");
    sb.append("    receiptNumber: ").append(toIndentedString(receiptNumber)).append("\n");
    sb.append("    bankNumber: ").append(toIndentedString(bankNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
