/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.apache.fineract.client.models.GetSelfBeneficiariesAccountOptions;
/**
 * GetSelfBeneficiariesTPTResponse
 */
@Schema(description = "GetSelfBeneficiariesTPTResponse")

public class GetSelfBeneficiariesTPTResponse {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("officeName")
  private String officeName = null;

  @SerializedName("clientName")
  private String clientName = null;

  @SerializedName("accountType")
  private GetSelfBeneficiariesAccountOptions accountType = null;

  @SerializedName("accountNumber")
  private Long accountNumber = null;

  @SerializedName("transferLimit")
  private Integer transferLimit = null;

  public GetSelfBeneficiariesTPTResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetSelfBeneficiariesTPTResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Client2Savings", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetSelfBeneficiariesTPTResponse officeName(String officeName) {
    this.officeName = officeName;
    return this;
  }

   /**
   * Get officeName
   * @return officeName
  **/
  @Schema(example = "Test Office", description = "")
  public String getOfficeName() {
    return officeName;
  }

  public void setOfficeName(String officeName) {
    this.officeName = officeName;
  }

  public GetSelfBeneficiariesTPTResponse clientName(String clientName) {
    this.clientName = clientName;
    return this;
  }

   /**
   * Get clientName
   * @return clientName
  **/
  @Schema(example = "FN2 LN2", description = "")
  public String getClientName() {
    return clientName;
  }

  public void setClientName(String clientName) {
    this.clientName = clientName;
  }

  public GetSelfBeneficiariesTPTResponse accountType(GetSelfBeneficiariesAccountOptions accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @Schema(description = "")
  public GetSelfBeneficiariesAccountOptions getAccountType() {
    return accountType;
  }

  public void setAccountType(GetSelfBeneficiariesAccountOptions accountType) {
    this.accountType = accountType;
  }

  public GetSelfBeneficiariesTPTResponse accountNumber(Long accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(example = "2", description = "")
  public Long getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(Long accountNumber) {
    this.accountNumber = accountNumber;
  }

  public GetSelfBeneficiariesTPTResponse transferLimit(Integer transferLimit) {
    this.transferLimit = transferLimit;
    return this;
  }

   /**
   * Get transferLimit
   * @return transferLimit
  **/
  @Schema(example = "0", description = "")
  public Integer getTransferLimit() {
    return transferLimit;
  }

  public void setTransferLimit(Integer transferLimit) {
    this.transferLimit = transferLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSelfBeneficiariesTPTResponse getSelfBeneficiariesTPTResponse = (GetSelfBeneficiariesTPTResponse) o;
    return Objects.equals(this.id, getSelfBeneficiariesTPTResponse.id) &&
        Objects.equals(this.name, getSelfBeneficiariesTPTResponse.name) &&
        Objects.equals(this.officeName, getSelfBeneficiariesTPTResponse.officeName) &&
        Objects.equals(this.clientName, getSelfBeneficiariesTPTResponse.clientName) &&
        Objects.equals(this.accountType, getSelfBeneficiariesTPTResponse.accountType) &&
        Objects.equals(this.accountNumber, getSelfBeneficiariesTPTResponse.accountNumber) &&
        Objects.equals(this.transferLimit, getSelfBeneficiariesTPTResponse.transferLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, officeName, clientName, accountType, accountNumber, transferLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSelfBeneficiariesTPTResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    officeName: ").append(toIndentedString(officeName)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    transferLimit: ").append(toIndentedString(transferLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
