/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.apache.fineract.client.models.Charge;
import org.apache.fineract.client.models.LoanProductConfigurableAttributes;
import org.apache.fineract.client.models.LoanProductFloatingRates;
import org.apache.fineract.client.models.LoanProductGuaranteeDetails;
import org.apache.fineract.client.models.LoanProductInterestRecalculationDetails;
import org.apache.fineract.client.models.LoanProductRelatedDetail;
import org.apache.fineract.client.models.LoanTransactionProcessingStrategy;
import org.apache.fineract.client.models.MonetaryCurrency;
import org.apache.fineract.client.models.Money;
import org.apache.fineract.client.models.Rate;
/**
 * LoanProduct
 */


public class LoanProduct {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("shortName")
  private String shortName = null;

  @SerializedName("rates")
  private List<Rate> rates = null;

  @SerializedName("loanProductRelatedDetail")
  private LoanProductRelatedDetail loanProductRelatedDetail = null;

  @SerializedName("includeInBorrowerCycle")
  private Boolean includeInBorrowerCycle = null;

  @SerializedName("startDate")
  private LocalDate startDate = null;

  @SerializedName("closeDate")
  private LocalDate closeDate = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("minimumDaysBetweenDisbursalAndFirstRepayment")
  private Integer minimumDaysBetweenDisbursalAndFirstRepayment = null;

  @SerializedName("productInterestRecalculationDetails")
  private LoanProductInterestRecalculationDetails productInterestRecalculationDetails = null;

  @SerializedName("loanProductGuaranteeDetails")
  private LoanProductGuaranteeDetails loanProductGuaranteeDetails = null;

  @SerializedName("principalThresholdForLastInstallment")
  private BigDecimal principalThresholdForLastInstallment = null;

  @SerializedName("installmentAmountInMultiplesOf")
  private Integer installmentAmountInMultiplesOf = null;

  @SerializedName("floatingRates")
  private LoanProductFloatingRates floatingRates = null;

  @SerializedName("syncExpectedWithDisbursementDate")
  private Boolean syncExpectedWithDisbursementDate = null;

  @SerializedName("currency")
  private MonetaryCurrency currency = null;

  @SerializedName("equalAmortization")
  private Boolean equalAmortization = null;

  @SerializedName("multiDisburseLoan")
  private Boolean multiDisburseLoan = null;

  @SerializedName("interestRecalculationEnabled")
  private Boolean interestRecalculationEnabled = null;

  @SerializedName("numberOfRepayments")
  private Integer numberOfRepayments = null;

  @SerializedName("nominalInterestRatePerPeriod")
  private BigDecimal nominalInterestRatePerPeriod = null;

  /**
   * Gets or Sets interestPeriodFrequencyType
   */
  @JsonAdapter(InterestPeriodFrequencyTypeEnum.Adapter.class)
  public enum InterestPeriodFrequencyTypeEnum {
    DAYS("DAYS"),
    WEEKS("WEEKS"),
    MONTHS("MONTHS"),
    YEARS("YEARS"),
    WHOLE_TERM("WHOLE_TERM"),
    INVALID("INVALID");

    private String value;

    InterestPeriodFrequencyTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static InterestPeriodFrequencyTypeEnum fromValue(String text) {
      for (InterestPeriodFrequencyTypeEnum b : InterestPeriodFrequencyTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<InterestPeriodFrequencyTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InterestPeriodFrequencyTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InterestPeriodFrequencyTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return InterestPeriodFrequencyTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("interestPeriodFrequencyType")
  private InterestPeriodFrequencyTypeEnum interestPeriodFrequencyType = null;

  @SerializedName("principalAmount")
  private Money principalAmount = null;

  @SerializedName("accountingType")
  private Integer accountingType = null;

  @SerializedName("linkedToFloatingInterestRate")
  private Boolean linkedToFloatingInterestRate = null;

  @SerializedName("cashBasedAccountingEnabled")
  private Boolean cashBasedAccountingEnabled = null;

  @SerializedName("upfrontAccrualAccountingEnabled")
  private Boolean upfrontAccrualAccountingEnabled = null;

  @SerializedName("accountingDisabled")
  private Boolean accountingDisabled = null;

  @SerializedName("periodicAccrualAccountingEnabled")
  private Boolean periodicAccrualAccountingEnabled = null;

  @SerializedName("holdGuaranteeFundsEnabled")
  private Boolean holdGuaranteeFundsEnabled = null;

  @SerializedName("accrualBasedAccountingEnabled")
  private Boolean accrualBasedAccountingEnabled = null;

  @SerializedName("repaymentStrategy")
  private LoanTransactionProcessingStrategy repaymentStrategy = null;

  @SerializedName("minNominalInterestRatePerPeriod")
  private BigDecimal minNominalInterestRatePerPeriod = null;

  @SerializedName("maxNominalInterestRatePerPeriod")
  private BigDecimal maxNominalInterestRatePerPeriod = null;

  @SerializedName("minNumberOfRepayments")
  private Integer minNumberOfRepayments = null;

  @SerializedName("maxNumberOfRepayments")
  private Integer maxNumberOfRepayments = null;

  @SerializedName("arrearsBasedOnOriginalSchedule")
  private Boolean arrearsBasedOnOriginalSchedule = null;

  @SerializedName("loanProductCharges")
  private List<Charge> loanProductCharges = null;

  @SerializedName("loanProductConfigurableAttributes")
  private LoanProductConfigurableAttributes loanProductConfigurableAttributes = null;

  @SerializedName("minPrincipalAmount")
  private Money minPrincipalAmount = null;

  @SerializedName("maxPrincipalAmount")
  private Money maxPrincipalAmount = null;

  @SerializedName("new")
  private Boolean _new = null;

  public LoanProduct id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LoanProduct shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @Schema(description = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public LoanProduct rates(List<Rate> rates) {
    this.rates = rates;
    return this;
  }

  public LoanProduct addRatesItem(Rate ratesItem) {
    if (this.rates == null) {
      this.rates = new ArrayList<>();
    }
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  @Schema(description = "")
  public List<Rate> getRates() {
    return rates;
  }

  public void setRates(List<Rate> rates) {
    this.rates = rates;
  }

  public LoanProduct loanProductRelatedDetail(LoanProductRelatedDetail loanProductRelatedDetail) {
    this.loanProductRelatedDetail = loanProductRelatedDetail;
    return this;
  }

   /**
   * Get loanProductRelatedDetail
   * @return loanProductRelatedDetail
  **/
  @Schema(description = "")
  public LoanProductRelatedDetail getLoanProductRelatedDetail() {
    return loanProductRelatedDetail;
  }

  public void setLoanProductRelatedDetail(LoanProductRelatedDetail loanProductRelatedDetail) {
    this.loanProductRelatedDetail = loanProductRelatedDetail;
  }

  public LoanProduct includeInBorrowerCycle(Boolean includeInBorrowerCycle) {
    this.includeInBorrowerCycle = includeInBorrowerCycle;
    return this;
  }

   /**
   * Get includeInBorrowerCycle
   * @return includeInBorrowerCycle
  **/
  @Schema(description = "")
  public Boolean isIncludeInBorrowerCycle() {
    return includeInBorrowerCycle;
  }

  public void setIncludeInBorrowerCycle(Boolean includeInBorrowerCycle) {
    this.includeInBorrowerCycle = includeInBorrowerCycle;
  }

  public LoanProduct startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @Schema(description = "")
  public LocalDate getStartDate() {
    return startDate;
  }

  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }

  public LoanProduct closeDate(LocalDate closeDate) {
    this.closeDate = closeDate;
    return this;
  }

   /**
   * Get closeDate
   * @return closeDate
  **/
  @Schema(description = "")
  public LocalDate getCloseDate() {
    return closeDate;
  }

  public void setCloseDate(LocalDate closeDate) {
    this.closeDate = closeDate;
  }

  public LoanProduct externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @Schema(description = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public LoanProduct minimumDaysBetweenDisbursalAndFirstRepayment(Integer minimumDaysBetweenDisbursalAndFirstRepayment) {
    this.minimumDaysBetweenDisbursalAndFirstRepayment = minimumDaysBetweenDisbursalAndFirstRepayment;
    return this;
  }

   /**
   * Get minimumDaysBetweenDisbursalAndFirstRepayment
   * @return minimumDaysBetweenDisbursalAndFirstRepayment
  **/
  @Schema(description = "")
  public Integer getMinimumDaysBetweenDisbursalAndFirstRepayment() {
    return minimumDaysBetweenDisbursalAndFirstRepayment;
  }

  public void setMinimumDaysBetweenDisbursalAndFirstRepayment(Integer minimumDaysBetweenDisbursalAndFirstRepayment) {
    this.minimumDaysBetweenDisbursalAndFirstRepayment = minimumDaysBetweenDisbursalAndFirstRepayment;
  }

  public LoanProduct productInterestRecalculationDetails(LoanProductInterestRecalculationDetails productInterestRecalculationDetails) {
    this.productInterestRecalculationDetails = productInterestRecalculationDetails;
    return this;
  }

   /**
   * Get productInterestRecalculationDetails
   * @return productInterestRecalculationDetails
  **/
  @Schema(description = "")
  public LoanProductInterestRecalculationDetails getProductInterestRecalculationDetails() {
    return productInterestRecalculationDetails;
  }

  public void setProductInterestRecalculationDetails(LoanProductInterestRecalculationDetails productInterestRecalculationDetails) {
    this.productInterestRecalculationDetails = productInterestRecalculationDetails;
  }

  public LoanProduct loanProductGuaranteeDetails(LoanProductGuaranteeDetails loanProductGuaranteeDetails) {
    this.loanProductGuaranteeDetails = loanProductGuaranteeDetails;
    return this;
  }

   /**
   * Get loanProductGuaranteeDetails
   * @return loanProductGuaranteeDetails
  **/
  @Schema(description = "")
  public LoanProductGuaranteeDetails getLoanProductGuaranteeDetails() {
    return loanProductGuaranteeDetails;
  }

  public void setLoanProductGuaranteeDetails(LoanProductGuaranteeDetails loanProductGuaranteeDetails) {
    this.loanProductGuaranteeDetails = loanProductGuaranteeDetails;
  }

  public LoanProduct principalThresholdForLastInstallment(BigDecimal principalThresholdForLastInstallment) {
    this.principalThresholdForLastInstallment = principalThresholdForLastInstallment;
    return this;
  }

   /**
   * Get principalThresholdForLastInstallment
   * @return principalThresholdForLastInstallment
  **/
  @Schema(description = "")
  public BigDecimal getPrincipalThresholdForLastInstallment() {
    return principalThresholdForLastInstallment;
  }

  public void setPrincipalThresholdForLastInstallment(BigDecimal principalThresholdForLastInstallment) {
    this.principalThresholdForLastInstallment = principalThresholdForLastInstallment;
  }

  public LoanProduct installmentAmountInMultiplesOf(Integer installmentAmountInMultiplesOf) {
    this.installmentAmountInMultiplesOf = installmentAmountInMultiplesOf;
    return this;
  }

   /**
   * Get installmentAmountInMultiplesOf
   * @return installmentAmountInMultiplesOf
  **/
  @Schema(description = "")
  public Integer getInstallmentAmountInMultiplesOf() {
    return installmentAmountInMultiplesOf;
  }

  public void setInstallmentAmountInMultiplesOf(Integer installmentAmountInMultiplesOf) {
    this.installmentAmountInMultiplesOf = installmentAmountInMultiplesOf;
  }

  public LoanProduct floatingRates(LoanProductFloatingRates floatingRates) {
    this.floatingRates = floatingRates;
    return this;
  }

   /**
   * Get floatingRates
   * @return floatingRates
  **/
  @Schema(description = "")
  public LoanProductFloatingRates getFloatingRates() {
    return floatingRates;
  }

  public void setFloatingRates(LoanProductFloatingRates floatingRates) {
    this.floatingRates = floatingRates;
  }

  public LoanProduct syncExpectedWithDisbursementDate(Boolean syncExpectedWithDisbursementDate) {
    this.syncExpectedWithDisbursementDate = syncExpectedWithDisbursementDate;
    return this;
  }

   /**
   * Get syncExpectedWithDisbursementDate
   * @return syncExpectedWithDisbursementDate
  **/
  @Schema(description = "")
  public Boolean isSyncExpectedWithDisbursementDate() {
    return syncExpectedWithDisbursementDate;
  }

  public void setSyncExpectedWithDisbursementDate(Boolean syncExpectedWithDisbursementDate) {
    this.syncExpectedWithDisbursementDate = syncExpectedWithDisbursementDate;
  }

  public LoanProduct currency(MonetaryCurrency currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public MonetaryCurrency getCurrency() {
    return currency;
  }

  public void setCurrency(MonetaryCurrency currency) {
    this.currency = currency;
  }

  public LoanProduct equalAmortization(Boolean equalAmortization) {
    this.equalAmortization = equalAmortization;
    return this;
  }

   /**
   * Get equalAmortization
   * @return equalAmortization
  **/
  @Schema(description = "")
  public Boolean isEqualAmortization() {
    return equalAmortization;
  }

  public void setEqualAmortization(Boolean equalAmortization) {
    this.equalAmortization = equalAmortization;
  }

  public LoanProduct multiDisburseLoan(Boolean multiDisburseLoan) {
    this.multiDisburseLoan = multiDisburseLoan;
    return this;
  }

   /**
   * Get multiDisburseLoan
   * @return multiDisburseLoan
  **/
  @Schema(description = "")
  public Boolean isMultiDisburseLoan() {
    return multiDisburseLoan;
  }

  public void setMultiDisburseLoan(Boolean multiDisburseLoan) {
    this.multiDisburseLoan = multiDisburseLoan;
  }

  public LoanProduct interestRecalculationEnabled(Boolean interestRecalculationEnabled) {
    this.interestRecalculationEnabled = interestRecalculationEnabled;
    return this;
  }

   /**
   * Get interestRecalculationEnabled
   * @return interestRecalculationEnabled
  **/
  @Schema(description = "")
  public Boolean isInterestRecalculationEnabled() {
    return interestRecalculationEnabled;
  }

  public void setInterestRecalculationEnabled(Boolean interestRecalculationEnabled) {
    this.interestRecalculationEnabled = interestRecalculationEnabled;
  }

  public LoanProduct numberOfRepayments(Integer numberOfRepayments) {
    this.numberOfRepayments = numberOfRepayments;
    return this;
  }

   /**
   * Get numberOfRepayments
   * @return numberOfRepayments
  **/
  @Schema(description = "")
  public Integer getNumberOfRepayments() {
    return numberOfRepayments;
  }

  public void setNumberOfRepayments(Integer numberOfRepayments) {
    this.numberOfRepayments = numberOfRepayments;
  }

  public LoanProduct nominalInterestRatePerPeriod(BigDecimal nominalInterestRatePerPeriod) {
    this.nominalInterestRatePerPeriod = nominalInterestRatePerPeriod;
    return this;
  }

   /**
   * Get nominalInterestRatePerPeriod
   * @return nominalInterestRatePerPeriod
  **/
  @Schema(description = "")
  public BigDecimal getNominalInterestRatePerPeriod() {
    return nominalInterestRatePerPeriod;
  }

  public void setNominalInterestRatePerPeriod(BigDecimal nominalInterestRatePerPeriod) {
    this.nominalInterestRatePerPeriod = nominalInterestRatePerPeriod;
  }

  public LoanProduct interestPeriodFrequencyType(InterestPeriodFrequencyTypeEnum interestPeriodFrequencyType) {
    this.interestPeriodFrequencyType = interestPeriodFrequencyType;
    return this;
  }

   /**
   * Get interestPeriodFrequencyType
   * @return interestPeriodFrequencyType
  **/
  @Schema(description = "")
  public InterestPeriodFrequencyTypeEnum getInterestPeriodFrequencyType() {
    return interestPeriodFrequencyType;
  }

  public void setInterestPeriodFrequencyType(InterestPeriodFrequencyTypeEnum interestPeriodFrequencyType) {
    this.interestPeriodFrequencyType = interestPeriodFrequencyType;
  }

  public LoanProduct principalAmount(Money principalAmount) {
    this.principalAmount = principalAmount;
    return this;
  }

   /**
   * Get principalAmount
   * @return principalAmount
  **/
  @Schema(description = "")
  public Money getPrincipalAmount() {
    return principalAmount;
  }

  public void setPrincipalAmount(Money principalAmount) {
    this.principalAmount = principalAmount;
  }

  public LoanProduct accountingType(Integer accountingType) {
    this.accountingType = accountingType;
    return this;
  }

   /**
   * Get accountingType
   * @return accountingType
  **/
  @Schema(description = "")
  public Integer getAccountingType() {
    return accountingType;
  }

  public void setAccountingType(Integer accountingType) {
    this.accountingType = accountingType;
  }

  public LoanProduct linkedToFloatingInterestRate(Boolean linkedToFloatingInterestRate) {
    this.linkedToFloatingInterestRate = linkedToFloatingInterestRate;
    return this;
  }

   /**
   * Get linkedToFloatingInterestRate
   * @return linkedToFloatingInterestRate
  **/
  @Schema(description = "")
  public Boolean isLinkedToFloatingInterestRate() {
    return linkedToFloatingInterestRate;
  }

  public void setLinkedToFloatingInterestRate(Boolean linkedToFloatingInterestRate) {
    this.linkedToFloatingInterestRate = linkedToFloatingInterestRate;
  }

  public LoanProduct cashBasedAccountingEnabled(Boolean cashBasedAccountingEnabled) {
    this.cashBasedAccountingEnabled = cashBasedAccountingEnabled;
    return this;
  }

   /**
   * Get cashBasedAccountingEnabled
   * @return cashBasedAccountingEnabled
  **/
  @Schema(description = "")
  public Boolean isCashBasedAccountingEnabled() {
    return cashBasedAccountingEnabled;
  }

  public void setCashBasedAccountingEnabled(Boolean cashBasedAccountingEnabled) {
    this.cashBasedAccountingEnabled = cashBasedAccountingEnabled;
  }

  public LoanProduct upfrontAccrualAccountingEnabled(Boolean upfrontAccrualAccountingEnabled) {
    this.upfrontAccrualAccountingEnabled = upfrontAccrualAccountingEnabled;
    return this;
  }

   /**
   * Get upfrontAccrualAccountingEnabled
   * @return upfrontAccrualAccountingEnabled
  **/
  @Schema(description = "")
  public Boolean isUpfrontAccrualAccountingEnabled() {
    return upfrontAccrualAccountingEnabled;
  }

  public void setUpfrontAccrualAccountingEnabled(Boolean upfrontAccrualAccountingEnabled) {
    this.upfrontAccrualAccountingEnabled = upfrontAccrualAccountingEnabled;
  }

  public LoanProduct accountingDisabled(Boolean accountingDisabled) {
    this.accountingDisabled = accountingDisabled;
    return this;
  }

   /**
   * Get accountingDisabled
   * @return accountingDisabled
  **/
  @Schema(description = "")
  public Boolean isAccountingDisabled() {
    return accountingDisabled;
  }

  public void setAccountingDisabled(Boolean accountingDisabled) {
    this.accountingDisabled = accountingDisabled;
  }

  public LoanProduct periodicAccrualAccountingEnabled(Boolean periodicAccrualAccountingEnabled) {
    this.periodicAccrualAccountingEnabled = periodicAccrualAccountingEnabled;
    return this;
  }

   /**
   * Get periodicAccrualAccountingEnabled
   * @return periodicAccrualAccountingEnabled
  **/
  @Schema(description = "")
  public Boolean isPeriodicAccrualAccountingEnabled() {
    return periodicAccrualAccountingEnabled;
  }

  public void setPeriodicAccrualAccountingEnabled(Boolean periodicAccrualAccountingEnabled) {
    this.periodicAccrualAccountingEnabled = periodicAccrualAccountingEnabled;
  }

  public LoanProduct holdGuaranteeFundsEnabled(Boolean holdGuaranteeFundsEnabled) {
    this.holdGuaranteeFundsEnabled = holdGuaranteeFundsEnabled;
    return this;
  }

   /**
   * Get holdGuaranteeFundsEnabled
   * @return holdGuaranteeFundsEnabled
  **/
  @Schema(description = "")
  public Boolean isHoldGuaranteeFundsEnabled() {
    return holdGuaranteeFundsEnabled;
  }

  public void setHoldGuaranteeFundsEnabled(Boolean holdGuaranteeFundsEnabled) {
    this.holdGuaranteeFundsEnabled = holdGuaranteeFundsEnabled;
  }

  public LoanProduct accrualBasedAccountingEnabled(Boolean accrualBasedAccountingEnabled) {
    this.accrualBasedAccountingEnabled = accrualBasedAccountingEnabled;
    return this;
  }

   /**
   * Get accrualBasedAccountingEnabled
   * @return accrualBasedAccountingEnabled
  **/
  @Schema(description = "")
  public Boolean isAccrualBasedAccountingEnabled() {
    return accrualBasedAccountingEnabled;
  }

  public void setAccrualBasedAccountingEnabled(Boolean accrualBasedAccountingEnabled) {
    this.accrualBasedAccountingEnabled = accrualBasedAccountingEnabled;
  }

  public LoanProduct repaymentStrategy(LoanTransactionProcessingStrategy repaymentStrategy) {
    this.repaymentStrategy = repaymentStrategy;
    return this;
  }

   /**
   * Get repaymentStrategy
   * @return repaymentStrategy
  **/
  @Schema(description = "")
  public LoanTransactionProcessingStrategy getRepaymentStrategy() {
    return repaymentStrategy;
  }

  public void setRepaymentStrategy(LoanTransactionProcessingStrategy repaymentStrategy) {
    this.repaymentStrategy = repaymentStrategy;
  }

  public LoanProduct minNominalInterestRatePerPeriod(BigDecimal minNominalInterestRatePerPeriod) {
    this.minNominalInterestRatePerPeriod = minNominalInterestRatePerPeriod;
    return this;
  }

   /**
   * Get minNominalInterestRatePerPeriod
   * @return minNominalInterestRatePerPeriod
  **/
  @Schema(description = "")
  public BigDecimal getMinNominalInterestRatePerPeriod() {
    return minNominalInterestRatePerPeriod;
  }

  public void setMinNominalInterestRatePerPeriod(BigDecimal minNominalInterestRatePerPeriod) {
    this.minNominalInterestRatePerPeriod = minNominalInterestRatePerPeriod;
  }

  public LoanProduct maxNominalInterestRatePerPeriod(BigDecimal maxNominalInterestRatePerPeriod) {
    this.maxNominalInterestRatePerPeriod = maxNominalInterestRatePerPeriod;
    return this;
  }

   /**
   * Get maxNominalInterestRatePerPeriod
   * @return maxNominalInterestRatePerPeriod
  **/
  @Schema(description = "")
  public BigDecimal getMaxNominalInterestRatePerPeriod() {
    return maxNominalInterestRatePerPeriod;
  }

  public void setMaxNominalInterestRatePerPeriod(BigDecimal maxNominalInterestRatePerPeriod) {
    this.maxNominalInterestRatePerPeriod = maxNominalInterestRatePerPeriod;
  }

  public LoanProduct minNumberOfRepayments(Integer minNumberOfRepayments) {
    this.minNumberOfRepayments = minNumberOfRepayments;
    return this;
  }

   /**
   * Get minNumberOfRepayments
   * @return minNumberOfRepayments
  **/
  @Schema(description = "")
  public Integer getMinNumberOfRepayments() {
    return minNumberOfRepayments;
  }

  public void setMinNumberOfRepayments(Integer minNumberOfRepayments) {
    this.minNumberOfRepayments = minNumberOfRepayments;
  }

  public LoanProduct maxNumberOfRepayments(Integer maxNumberOfRepayments) {
    this.maxNumberOfRepayments = maxNumberOfRepayments;
    return this;
  }

   /**
   * Get maxNumberOfRepayments
   * @return maxNumberOfRepayments
  **/
  @Schema(description = "")
  public Integer getMaxNumberOfRepayments() {
    return maxNumberOfRepayments;
  }

  public void setMaxNumberOfRepayments(Integer maxNumberOfRepayments) {
    this.maxNumberOfRepayments = maxNumberOfRepayments;
  }

  public LoanProduct arrearsBasedOnOriginalSchedule(Boolean arrearsBasedOnOriginalSchedule) {
    this.arrearsBasedOnOriginalSchedule = arrearsBasedOnOriginalSchedule;
    return this;
  }

   /**
   * Get arrearsBasedOnOriginalSchedule
   * @return arrearsBasedOnOriginalSchedule
  **/
  @Schema(description = "")
  public Boolean isArrearsBasedOnOriginalSchedule() {
    return arrearsBasedOnOriginalSchedule;
  }

  public void setArrearsBasedOnOriginalSchedule(Boolean arrearsBasedOnOriginalSchedule) {
    this.arrearsBasedOnOriginalSchedule = arrearsBasedOnOriginalSchedule;
  }

  public LoanProduct loanProductCharges(List<Charge> loanProductCharges) {
    this.loanProductCharges = loanProductCharges;
    return this;
  }

  public LoanProduct addLoanProductChargesItem(Charge loanProductChargesItem) {
    if (this.loanProductCharges == null) {
      this.loanProductCharges = new ArrayList<>();
    }
    this.loanProductCharges.add(loanProductChargesItem);
    return this;
  }

   /**
   * Get loanProductCharges
   * @return loanProductCharges
  **/
  @Schema(description = "")
  public List<Charge> getLoanProductCharges() {
    return loanProductCharges;
  }

  public void setLoanProductCharges(List<Charge> loanProductCharges) {
    this.loanProductCharges = loanProductCharges;
  }

  public LoanProduct loanProductConfigurableAttributes(LoanProductConfigurableAttributes loanProductConfigurableAttributes) {
    this.loanProductConfigurableAttributes = loanProductConfigurableAttributes;
    return this;
  }

   /**
   * Get loanProductConfigurableAttributes
   * @return loanProductConfigurableAttributes
  **/
  @Schema(description = "")
  public LoanProductConfigurableAttributes getLoanProductConfigurableAttributes() {
    return loanProductConfigurableAttributes;
  }

  public void setLoanProductConfigurableAttributes(LoanProductConfigurableAttributes loanProductConfigurableAttributes) {
    this.loanProductConfigurableAttributes = loanProductConfigurableAttributes;
  }

  public LoanProduct minPrincipalAmount(Money minPrincipalAmount) {
    this.minPrincipalAmount = minPrincipalAmount;
    return this;
  }

   /**
   * Get minPrincipalAmount
   * @return minPrincipalAmount
  **/
  @Schema(description = "")
  public Money getMinPrincipalAmount() {
    return minPrincipalAmount;
  }

  public void setMinPrincipalAmount(Money minPrincipalAmount) {
    this.minPrincipalAmount = minPrincipalAmount;
  }

  public LoanProduct maxPrincipalAmount(Money maxPrincipalAmount) {
    this.maxPrincipalAmount = maxPrincipalAmount;
    return this;
  }

   /**
   * Get maxPrincipalAmount
   * @return maxPrincipalAmount
  **/
  @Schema(description = "")
  public Money getMaxPrincipalAmount() {
    return maxPrincipalAmount;
  }

  public void setMaxPrincipalAmount(Money maxPrincipalAmount) {
    this.maxPrincipalAmount = maxPrincipalAmount;
  }

  public LoanProduct _new(Boolean _new) {
    this._new = _new;
    return this;
  }

   /**
   * Get _new
   * @return _new
  **/
  @Schema(description = "")
  public Boolean isNew() {
    return _new;
  }

  public void setNew(Boolean _new) {
    this._new = _new;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanProduct loanProduct = (LoanProduct) o;
    return Objects.equals(this.id, loanProduct.id) &&
        Objects.equals(this.shortName, loanProduct.shortName) &&
        Objects.equals(this.rates, loanProduct.rates) &&
        Objects.equals(this.loanProductRelatedDetail, loanProduct.loanProductRelatedDetail) &&
        Objects.equals(this.includeInBorrowerCycle, loanProduct.includeInBorrowerCycle) &&
        Objects.equals(this.startDate, loanProduct.startDate) &&
        Objects.equals(this.closeDate, loanProduct.closeDate) &&
        Objects.equals(this.externalId, loanProduct.externalId) &&
        Objects.equals(this.minimumDaysBetweenDisbursalAndFirstRepayment, loanProduct.minimumDaysBetweenDisbursalAndFirstRepayment) &&
        Objects.equals(this.productInterestRecalculationDetails, loanProduct.productInterestRecalculationDetails) &&
        Objects.equals(this.loanProductGuaranteeDetails, loanProduct.loanProductGuaranteeDetails) &&
        Objects.equals(this.principalThresholdForLastInstallment, loanProduct.principalThresholdForLastInstallment) &&
        Objects.equals(this.installmentAmountInMultiplesOf, loanProduct.installmentAmountInMultiplesOf) &&
        Objects.equals(this.floatingRates, loanProduct.floatingRates) &&
        Objects.equals(this.syncExpectedWithDisbursementDate, loanProduct.syncExpectedWithDisbursementDate) &&
        Objects.equals(this.currency, loanProduct.currency) &&
        Objects.equals(this.equalAmortization, loanProduct.equalAmortization) &&
        Objects.equals(this.multiDisburseLoan, loanProduct.multiDisburseLoan) &&
        Objects.equals(this.interestRecalculationEnabled, loanProduct.interestRecalculationEnabled) &&
        Objects.equals(this.numberOfRepayments, loanProduct.numberOfRepayments) &&
        Objects.equals(this.nominalInterestRatePerPeriod, loanProduct.nominalInterestRatePerPeriod) &&
        Objects.equals(this.interestPeriodFrequencyType, loanProduct.interestPeriodFrequencyType) &&
        Objects.equals(this.principalAmount, loanProduct.principalAmount) &&
        Objects.equals(this.accountingType, loanProduct.accountingType) &&
        Objects.equals(this.linkedToFloatingInterestRate, loanProduct.linkedToFloatingInterestRate) &&
        Objects.equals(this.cashBasedAccountingEnabled, loanProduct.cashBasedAccountingEnabled) &&
        Objects.equals(this.upfrontAccrualAccountingEnabled, loanProduct.upfrontAccrualAccountingEnabled) &&
        Objects.equals(this.accountingDisabled, loanProduct.accountingDisabled) &&
        Objects.equals(this.periodicAccrualAccountingEnabled, loanProduct.periodicAccrualAccountingEnabled) &&
        Objects.equals(this.holdGuaranteeFundsEnabled, loanProduct.holdGuaranteeFundsEnabled) &&
        Objects.equals(this.accrualBasedAccountingEnabled, loanProduct.accrualBasedAccountingEnabled) &&
        Objects.equals(this.repaymentStrategy, loanProduct.repaymentStrategy) &&
        Objects.equals(this.minNominalInterestRatePerPeriod, loanProduct.minNominalInterestRatePerPeriod) &&
        Objects.equals(this.maxNominalInterestRatePerPeriod, loanProduct.maxNominalInterestRatePerPeriod) &&
        Objects.equals(this.minNumberOfRepayments, loanProduct.minNumberOfRepayments) &&
        Objects.equals(this.maxNumberOfRepayments, loanProduct.maxNumberOfRepayments) &&
        Objects.equals(this.arrearsBasedOnOriginalSchedule, loanProduct.arrearsBasedOnOriginalSchedule) &&
        Objects.equals(this.loanProductCharges, loanProduct.loanProductCharges) &&
        Objects.equals(this.loanProductConfigurableAttributes, loanProduct.loanProductConfigurableAttributes) &&
        Objects.equals(this.minPrincipalAmount, loanProduct.minPrincipalAmount) &&
        Objects.equals(this.maxPrincipalAmount, loanProduct.maxPrincipalAmount) &&
        Objects.equals(this._new, loanProduct._new);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shortName, rates, loanProductRelatedDetail, includeInBorrowerCycle, startDate, closeDate, externalId, minimumDaysBetweenDisbursalAndFirstRepayment, productInterestRecalculationDetails, loanProductGuaranteeDetails, principalThresholdForLastInstallment, installmentAmountInMultiplesOf, floatingRates, syncExpectedWithDisbursementDate, currency, equalAmortization, multiDisburseLoan, interestRecalculationEnabled, numberOfRepayments, nominalInterestRatePerPeriod, interestPeriodFrequencyType, principalAmount, accountingType, linkedToFloatingInterestRate, cashBasedAccountingEnabled, upfrontAccrualAccountingEnabled, accountingDisabled, periodicAccrualAccountingEnabled, holdGuaranteeFundsEnabled, accrualBasedAccountingEnabled, repaymentStrategy, minNominalInterestRatePerPeriod, maxNominalInterestRatePerPeriod, minNumberOfRepayments, maxNumberOfRepayments, arrearsBasedOnOriginalSchedule, loanProductCharges, loanProductConfigurableAttributes, minPrincipalAmount, maxPrincipalAmount, _new);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanProduct {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("    loanProductRelatedDetail: ").append(toIndentedString(loanProductRelatedDetail)).append("\n");
    sb.append("    includeInBorrowerCycle: ").append(toIndentedString(includeInBorrowerCycle)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    closeDate: ").append(toIndentedString(closeDate)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    minimumDaysBetweenDisbursalAndFirstRepayment: ").append(toIndentedString(minimumDaysBetweenDisbursalAndFirstRepayment)).append("\n");
    sb.append("    productInterestRecalculationDetails: ").append(toIndentedString(productInterestRecalculationDetails)).append("\n");
    sb.append("    loanProductGuaranteeDetails: ").append(toIndentedString(loanProductGuaranteeDetails)).append("\n");
    sb.append("    principalThresholdForLastInstallment: ").append(toIndentedString(principalThresholdForLastInstallment)).append("\n");
    sb.append("    installmentAmountInMultiplesOf: ").append(toIndentedString(installmentAmountInMultiplesOf)).append("\n");
    sb.append("    floatingRates: ").append(toIndentedString(floatingRates)).append("\n");
    sb.append("    syncExpectedWithDisbursementDate: ").append(toIndentedString(syncExpectedWithDisbursementDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    equalAmortization: ").append(toIndentedString(equalAmortization)).append("\n");
    sb.append("    multiDisburseLoan: ").append(toIndentedString(multiDisburseLoan)).append("\n");
    sb.append("    interestRecalculationEnabled: ").append(toIndentedString(interestRecalculationEnabled)).append("\n");
    sb.append("    numberOfRepayments: ").append(toIndentedString(numberOfRepayments)).append("\n");
    sb.append("    nominalInterestRatePerPeriod: ").append(toIndentedString(nominalInterestRatePerPeriod)).append("\n");
    sb.append("    interestPeriodFrequencyType: ").append(toIndentedString(interestPeriodFrequencyType)).append("\n");
    sb.append("    principalAmount: ").append(toIndentedString(principalAmount)).append("\n");
    sb.append("    accountingType: ").append(toIndentedString(accountingType)).append("\n");
    sb.append("    linkedToFloatingInterestRate: ").append(toIndentedString(linkedToFloatingInterestRate)).append("\n");
    sb.append("    cashBasedAccountingEnabled: ").append(toIndentedString(cashBasedAccountingEnabled)).append("\n");
    sb.append("    upfrontAccrualAccountingEnabled: ").append(toIndentedString(upfrontAccrualAccountingEnabled)).append("\n");
    sb.append("    accountingDisabled: ").append(toIndentedString(accountingDisabled)).append("\n");
    sb.append("    periodicAccrualAccountingEnabled: ").append(toIndentedString(periodicAccrualAccountingEnabled)).append("\n");
    sb.append("    holdGuaranteeFundsEnabled: ").append(toIndentedString(holdGuaranteeFundsEnabled)).append("\n");
    sb.append("    accrualBasedAccountingEnabled: ").append(toIndentedString(accrualBasedAccountingEnabled)).append("\n");
    sb.append("    repaymentStrategy: ").append(toIndentedString(repaymentStrategy)).append("\n");
    sb.append("    minNominalInterestRatePerPeriod: ").append(toIndentedString(minNominalInterestRatePerPeriod)).append("\n");
    sb.append("    maxNominalInterestRatePerPeriod: ").append(toIndentedString(maxNominalInterestRatePerPeriod)).append("\n");
    sb.append("    minNumberOfRepayments: ").append(toIndentedString(minNumberOfRepayments)).append("\n");
    sb.append("    maxNumberOfRepayments: ").append(toIndentedString(maxNumberOfRepayments)).append("\n");
    sb.append("    arrearsBasedOnOriginalSchedule: ").append(toIndentedString(arrearsBasedOnOriginalSchedule)).append("\n");
    sb.append("    loanProductCharges: ").append(toIndentedString(loanProductCharges)).append("\n");
    sb.append("    loanProductConfigurableAttributes: ").append(toIndentedString(loanProductConfigurableAttributes)).append("\n");
    sb.append("    minPrincipalAmount: ").append(toIndentedString(minPrincipalAmount)).append("\n");
    sb.append("    maxPrincipalAmount: ").append(toIndentedString(maxPrincipalAmount)).append("\n");
    sb.append("    _new: ").append(toIndentedString(_new)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
