/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PostAccountTransfersRequest
 */
@Schema(description = "PostAccountTransfersRequest")

public class PostAccountTransfersRequest {
  @SerializedName("fromOfficeId")
  private Integer fromOfficeId = null;

  @SerializedName("fromClientId")
  private Integer fromClientId = null;

  @SerializedName("fromAccountType")
  private Integer fromAccountType = null;

  @SerializedName("fromAccountId")
  private Integer fromAccountId = null;

  @SerializedName("toOfficeId")
  private Integer toOfficeId = null;

  @SerializedName("toClientId")
  private Integer toClientId = null;

  @SerializedName("toAccountType")
  private Integer toAccountType = null;

  @SerializedName("toAccountId")
  private Integer toAccountId = null;

  @SerializedName("dateFormat")
  private String dateFormat = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("transferDate")
  private String transferDate = null;

  @SerializedName("transferAmount")
  private Float transferAmount = null;

  @SerializedName("transferDescription")
  private String transferDescription = null;

  public PostAccountTransfersRequest fromOfficeId(Integer fromOfficeId) {
    this.fromOfficeId = fromOfficeId;
    return this;
  }

   /**
   * Get fromOfficeId
   * @return fromOfficeId
  **/
  @Schema(example = "1", description = "")
  public Integer getFromOfficeId() {
    return fromOfficeId;
  }

  public void setFromOfficeId(Integer fromOfficeId) {
    this.fromOfficeId = fromOfficeId;
  }

  public PostAccountTransfersRequest fromClientId(Integer fromClientId) {
    this.fromClientId = fromClientId;
    return this;
  }

   /**
   * Get fromClientId
   * @return fromClientId
  **/
  @Schema(example = "1", description = "")
  public Integer getFromClientId() {
    return fromClientId;
  }

  public void setFromClientId(Integer fromClientId) {
    this.fromClientId = fromClientId;
  }

  public PostAccountTransfersRequest fromAccountType(Integer fromAccountType) {
    this.fromAccountType = fromAccountType;
    return this;
  }

   /**
   * Get fromAccountType
   * @return fromAccountType
  **/
  @Schema(example = "2", description = "")
  public Integer getFromAccountType() {
    return fromAccountType;
  }

  public void setFromAccountType(Integer fromAccountType) {
    this.fromAccountType = fromAccountType;
  }

  public PostAccountTransfersRequest fromAccountId(Integer fromAccountId) {
    this.fromAccountId = fromAccountId;
    return this;
  }

   /**
   * Get fromAccountId
   * @return fromAccountId
  **/
  @Schema(example = "1", description = "")
  public Integer getFromAccountId() {
    return fromAccountId;
  }

  public void setFromAccountId(Integer fromAccountId) {
    this.fromAccountId = fromAccountId;
  }

  public PostAccountTransfersRequest toOfficeId(Integer toOfficeId) {
    this.toOfficeId = toOfficeId;
    return this;
  }

   /**
   * Get toOfficeId
   * @return toOfficeId
  **/
  @Schema(example = "1", description = "")
  public Integer getToOfficeId() {
    return toOfficeId;
  }

  public void setToOfficeId(Integer toOfficeId) {
    this.toOfficeId = toOfficeId;
  }

  public PostAccountTransfersRequest toClientId(Integer toClientId) {
    this.toClientId = toClientId;
    return this;
  }

   /**
   * Get toClientId
   * @return toClientId
  **/
  @Schema(example = "1", description = "")
  public Integer getToClientId() {
    return toClientId;
  }

  public void setToClientId(Integer toClientId) {
    this.toClientId = toClientId;
  }

  public PostAccountTransfersRequest toAccountType(Integer toAccountType) {
    this.toAccountType = toAccountType;
    return this;
  }

   /**
   * Get toAccountType
   * @return toAccountType
  **/
  @Schema(example = "2", description = "")
  public Integer getToAccountType() {
    return toAccountType;
  }

  public void setToAccountType(Integer toAccountType) {
    this.toAccountType = toAccountType;
  }

  public PostAccountTransfersRequest toAccountId(Integer toAccountId) {
    this.toAccountId = toAccountId;
    return this;
  }

   /**
   * Get toAccountId
   * @return toAccountId
  **/
  @Schema(example = "2", description = "")
  public Integer getToAccountId() {
    return toAccountId;
  }

  public void setToAccountId(Integer toAccountId) {
    this.toAccountId = toAccountId;
  }

  public PostAccountTransfersRequest dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  @Schema(example = "dd MMMM yyyy", description = "")
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public PostAccountTransfersRequest locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @Schema(example = "en", description = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public PostAccountTransfersRequest transferDate(String transferDate) {
    this.transferDate = transferDate;
    return this;
  }

   /**
   * Get transferDate
   * @return transferDate
  **/
  @Schema(example = "01 August 2011", description = "")
  public String getTransferDate() {
    return transferDate;
  }

  public void setTransferDate(String transferDate) {
    this.transferDate = transferDate;
  }

  public PostAccountTransfersRequest transferAmount(Float transferAmount) {
    this.transferAmount = transferAmount;
    return this;
  }

   /**
   * Get transferAmount
   * @return transferAmount
  **/
  @Schema(example = "112.45", description = "")
  public Float getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(Float transferAmount) {
    this.transferAmount = transferAmount;
  }

  public PostAccountTransfersRequest transferDescription(String transferDescription) {
    this.transferDescription = transferDescription;
    return this;
  }

   /**
   * Get transferDescription
   * @return transferDescription
  **/
  @Schema(example = "A description of the transfer", description = "")
  public String getTransferDescription() {
    return transferDescription;
  }

  public void setTransferDescription(String transferDescription) {
    this.transferDescription = transferDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostAccountTransfersRequest postAccountTransfersRequest = (PostAccountTransfersRequest) o;
    return Objects.equals(this.fromOfficeId, postAccountTransfersRequest.fromOfficeId) &&
        Objects.equals(this.fromClientId, postAccountTransfersRequest.fromClientId) &&
        Objects.equals(this.fromAccountType, postAccountTransfersRequest.fromAccountType) &&
        Objects.equals(this.fromAccountId, postAccountTransfersRequest.fromAccountId) &&
        Objects.equals(this.toOfficeId, postAccountTransfersRequest.toOfficeId) &&
        Objects.equals(this.toClientId, postAccountTransfersRequest.toClientId) &&
        Objects.equals(this.toAccountType, postAccountTransfersRequest.toAccountType) &&
        Objects.equals(this.toAccountId, postAccountTransfersRequest.toAccountId) &&
        Objects.equals(this.dateFormat, postAccountTransfersRequest.dateFormat) &&
        Objects.equals(this.locale, postAccountTransfersRequest.locale) &&
        Objects.equals(this.transferDate, postAccountTransfersRequest.transferDate) &&
        Objects.equals(this.transferAmount, postAccountTransfersRequest.transferAmount) &&
        Objects.equals(this.transferDescription, postAccountTransfersRequest.transferDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromOfficeId, fromClientId, fromAccountType, fromAccountId, toOfficeId, toClientId, toAccountType, toAccountId, dateFormat, locale, transferDate, transferAmount, transferDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostAccountTransfersRequest {\n");
    
    sb.append("    fromOfficeId: ").append(toIndentedString(fromOfficeId)).append("\n");
    sb.append("    fromClientId: ").append(toIndentedString(fromClientId)).append("\n");
    sb.append("    fromAccountType: ").append(toIndentedString(fromAccountType)).append("\n");
    sb.append("    fromAccountId: ").append(toIndentedString(fromAccountId)).append("\n");
    sb.append("    toOfficeId: ").append(toIndentedString(toOfficeId)).append("\n");
    sb.append("    toClientId: ").append(toIndentedString(toClientId)).append("\n");
    sb.append("    toAccountType: ").append(toIndentedString(toAccountType)).append("\n");
    sb.append("    toAccountId: ").append(toIndentedString(toAccountId)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    transferDate: ").append(toIndentedString(transferDate)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    transferDescription: ").append(toIndentedString(transferDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
