/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PostLoansRequest
 */
@Schema(description = "PostLoansRequest")

public class PostLoansRequest {
  @SerializedName("dateFormat")
  private String dateFormat = null;

  @SerializedName("locale")
  private String locale = null;

  @SerializedName("productId")
  private Integer productId = null;

  @SerializedName("principal")
  private Double principal = null;

  @SerializedName("loanTermFrequency")
  private Integer loanTermFrequency = null;

  @SerializedName("loanTermFrequencyType")
  private Integer loanTermFrequencyType = null;

  @SerializedName("numberOfRepayments")
  private Integer numberOfRepayments = null;

  @SerializedName("repaymentEvery")
  private Integer repaymentEvery = null;

  @SerializedName("repaymentFrequencyType")
  private Integer repaymentFrequencyType = null;

  @SerializedName("interestRatePerPeriod")
  private Integer interestRatePerPeriod = null;

  @SerializedName("amortizationType")
  private Integer amortizationType = null;

  @SerializedName("interestType")
  private Integer interestType = null;

  @SerializedName("interestCalculationPeriodType")
  private Integer interestCalculationPeriodType = null;

  @SerializedName("expectedDisbursementDate")
  private String expectedDisbursementDate = null;

  @SerializedName("transactionProcessingStrategyId")
  private Integer transactionProcessingStrategyId = null;

  public PostLoansRequest dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  @Schema(example = "dd MMMM yyyy", description = "")
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public PostLoansRequest locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @Schema(example = "en_GB", description = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public PostLoansRequest productId(Integer productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @Schema(example = "1", description = "")
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  public PostLoansRequest principal(Double principal) {
    this.principal = principal;
    return this;
  }

   /**
   * Get principal
   * @return principal
  **/
  @Schema(description = "")
  public Double getPrincipal() {
    return principal;
  }

  public void setPrincipal(Double principal) {
    this.principal = principal;
  }

  public PostLoansRequest loanTermFrequency(Integer loanTermFrequency) {
    this.loanTermFrequency = loanTermFrequency;
    return this;
  }

   /**
   * Get loanTermFrequency
   * @return loanTermFrequency
  **/
  @Schema(example = "12", description = "")
  public Integer getLoanTermFrequency() {
    return loanTermFrequency;
  }

  public void setLoanTermFrequency(Integer loanTermFrequency) {
    this.loanTermFrequency = loanTermFrequency;
  }

  public PostLoansRequest loanTermFrequencyType(Integer loanTermFrequencyType) {
    this.loanTermFrequencyType = loanTermFrequencyType;
    return this;
  }

   /**
   * Get loanTermFrequencyType
   * @return loanTermFrequencyType
  **/
  @Schema(example = "2", description = "")
  public Integer getLoanTermFrequencyType() {
    return loanTermFrequencyType;
  }

  public void setLoanTermFrequencyType(Integer loanTermFrequencyType) {
    this.loanTermFrequencyType = loanTermFrequencyType;
  }

  public PostLoansRequest numberOfRepayments(Integer numberOfRepayments) {
    this.numberOfRepayments = numberOfRepayments;
    return this;
  }

   /**
   * Get numberOfRepayments
   * @return numberOfRepayments
  **/
  @Schema(example = "12", description = "")
  public Integer getNumberOfRepayments() {
    return numberOfRepayments;
  }

  public void setNumberOfRepayments(Integer numberOfRepayments) {
    this.numberOfRepayments = numberOfRepayments;
  }

  public PostLoansRequest repaymentEvery(Integer repaymentEvery) {
    this.repaymentEvery = repaymentEvery;
    return this;
  }

   /**
   * Get repaymentEvery
   * @return repaymentEvery
  **/
  @Schema(example = "1", description = "")
  public Integer getRepaymentEvery() {
    return repaymentEvery;
  }

  public void setRepaymentEvery(Integer repaymentEvery) {
    this.repaymentEvery = repaymentEvery;
  }

  public PostLoansRequest repaymentFrequencyType(Integer repaymentFrequencyType) {
    this.repaymentFrequencyType = repaymentFrequencyType;
    return this;
  }

   /**
   * Get repaymentFrequencyType
   * @return repaymentFrequencyType
  **/
  @Schema(example = "2", description = "")
  public Integer getRepaymentFrequencyType() {
    return repaymentFrequencyType;
  }

  public void setRepaymentFrequencyType(Integer repaymentFrequencyType) {
    this.repaymentFrequencyType = repaymentFrequencyType;
  }

  public PostLoansRequest interestRatePerPeriod(Integer interestRatePerPeriod) {
    this.interestRatePerPeriod = interestRatePerPeriod;
    return this;
  }

   /**
   * Get interestRatePerPeriod
   * @return interestRatePerPeriod
  **/
  @Schema(example = "2", description = "")
  public Integer getInterestRatePerPeriod() {
    return interestRatePerPeriod;
  }

  public void setInterestRatePerPeriod(Integer interestRatePerPeriod) {
    this.interestRatePerPeriod = interestRatePerPeriod;
  }

  public PostLoansRequest amortizationType(Integer amortizationType) {
    this.amortizationType = amortizationType;
    return this;
  }

   /**
   * Get amortizationType
   * @return amortizationType
  **/
  @Schema(example = "1", description = "")
  public Integer getAmortizationType() {
    return amortizationType;
  }

  public void setAmortizationType(Integer amortizationType) {
    this.amortizationType = amortizationType;
  }

  public PostLoansRequest interestType(Integer interestType) {
    this.interestType = interestType;
    return this;
  }

   /**
   * Get interestType
   * @return interestType
  **/
  @Schema(example = "0", description = "")
  public Integer getInterestType() {
    return interestType;
  }

  public void setInterestType(Integer interestType) {
    this.interestType = interestType;
  }

  public PostLoansRequest interestCalculationPeriodType(Integer interestCalculationPeriodType) {
    this.interestCalculationPeriodType = interestCalculationPeriodType;
    return this;
  }

   /**
   * Get interestCalculationPeriodType
   * @return interestCalculationPeriodType
  **/
  @Schema(example = "1", description = "")
  public Integer getInterestCalculationPeriodType() {
    return interestCalculationPeriodType;
  }

  public void setInterestCalculationPeriodType(Integer interestCalculationPeriodType) {
    this.interestCalculationPeriodType = interestCalculationPeriodType;
  }

  public PostLoansRequest expectedDisbursementDate(String expectedDisbursementDate) {
    this.expectedDisbursementDate = expectedDisbursementDate;
    return this;
  }

   /**
   * Get expectedDisbursementDate
   * @return expectedDisbursementDate
  **/
  @Schema(example = "20 September 2011", description = "")
  public String getExpectedDisbursementDate() {
    return expectedDisbursementDate;
  }

  public void setExpectedDisbursementDate(String expectedDisbursementDate) {
    this.expectedDisbursementDate = expectedDisbursementDate;
  }

  public PostLoansRequest transactionProcessingStrategyId(Integer transactionProcessingStrategyId) {
    this.transactionProcessingStrategyId = transactionProcessingStrategyId;
    return this;
  }

   /**
   * Get transactionProcessingStrategyId
   * @return transactionProcessingStrategyId
  **/
  @Schema(example = "2", description = "")
  public Integer getTransactionProcessingStrategyId() {
    return transactionProcessingStrategyId;
  }

  public void setTransactionProcessingStrategyId(Integer transactionProcessingStrategyId) {
    this.transactionProcessingStrategyId = transactionProcessingStrategyId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostLoansRequest postLoansRequest = (PostLoansRequest) o;
    return Objects.equals(this.dateFormat, postLoansRequest.dateFormat) &&
        Objects.equals(this.locale, postLoansRequest.locale) &&
        Objects.equals(this.productId, postLoansRequest.productId) &&
        Objects.equals(this.principal, postLoansRequest.principal) &&
        Objects.equals(this.loanTermFrequency, postLoansRequest.loanTermFrequency) &&
        Objects.equals(this.loanTermFrequencyType, postLoansRequest.loanTermFrequencyType) &&
        Objects.equals(this.numberOfRepayments, postLoansRequest.numberOfRepayments) &&
        Objects.equals(this.repaymentEvery, postLoansRequest.repaymentEvery) &&
        Objects.equals(this.repaymentFrequencyType, postLoansRequest.repaymentFrequencyType) &&
        Objects.equals(this.interestRatePerPeriod, postLoansRequest.interestRatePerPeriod) &&
        Objects.equals(this.amortizationType, postLoansRequest.amortizationType) &&
        Objects.equals(this.interestType, postLoansRequest.interestType) &&
        Objects.equals(this.interestCalculationPeriodType, postLoansRequest.interestCalculationPeriodType) &&
        Objects.equals(this.expectedDisbursementDate, postLoansRequest.expectedDisbursementDate) &&
        Objects.equals(this.transactionProcessingStrategyId, postLoansRequest.transactionProcessingStrategyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateFormat, locale, productId, principal, loanTermFrequency, loanTermFrequencyType, numberOfRepayments, repaymentEvery, repaymentFrequencyType, interestRatePerPeriod, amortizationType, interestType, interestCalculationPeriodType, expectedDisbursementDate, transactionProcessingStrategyId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostLoansRequest {\n");
    
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    principal: ").append(toIndentedString(principal)).append("\n");
    sb.append("    loanTermFrequency: ").append(toIndentedString(loanTermFrequency)).append("\n");
    sb.append("    loanTermFrequencyType: ").append(toIndentedString(loanTermFrequencyType)).append("\n");
    sb.append("    numberOfRepayments: ").append(toIndentedString(numberOfRepayments)).append("\n");
    sb.append("    repaymentEvery: ").append(toIndentedString(repaymentEvery)).append("\n");
    sb.append("    repaymentFrequencyType: ").append(toIndentedString(repaymentFrequencyType)).append("\n");
    sb.append("    interestRatePerPeriod: ").append(toIndentedString(interestRatePerPeriod)).append("\n");
    sb.append("    amortizationType: ").append(toIndentedString(amortizationType)).append("\n");
    sb.append("    interestType: ").append(toIndentedString(interestType)).append("\n");
    sb.append("    interestCalculationPeriodType: ").append(toIndentedString(interestCalculationPeriodType)).append("\n");
    sb.append("    expectedDisbursementDate: ").append(toIndentedString(expectedDisbursementDate)).append("\n");
    sb.append("    transactionProcessingStrategyId: ").append(toIndentedString(transactionProcessingStrategyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
