/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PutDataTablesAppTableIdDatatableIdRequest
 */
@Schema(description = "PutDataTablesAppTableIdDatatableIdRequest")

public class PutDataTablesAppTableIdDatatableIdRequest {
  @SerializedName("DateOfBirth")
  private String dateOfBirth = null;

  @SerializedName("Education_cdHighest")
  private Long educationCdHighest = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("OtherNotes")
  private String otherNotes = null;

  @SerializedName("PointsScore")
  private Long pointsScore = null;

  @SerializedName("dateFormat")
  private String dateFormat = null;

  @SerializedName("locale")
  private String locale = null;

  public PutDataTablesAppTableIdDatatableIdRequest dateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @Schema(example = "01 June 1982", description = "")
  public String getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public PutDataTablesAppTableIdDatatableIdRequest educationCdHighest(Long educationCdHighest) {
    this.educationCdHighest = educationCdHighest;
    return this;
  }

   /**
   * Get educationCdHighest
   * @return educationCdHighest
  **/
  @Schema(example = "5", description = "")
  public Long getEducationCdHighest() {
    return educationCdHighest;
  }

  public void setEducationCdHighest(Long educationCdHighest) {
    this.educationCdHighest = educationCdHighest;
  }

  public PutDataTablesAppTableIdDatatableIdRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "June", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PutDataTablesAppTableIdDatatableIdRequest otherNotes(String otherNotes) {
    this.otherNotes = otherNotes;
    return this;
  }

   /**
   * Get otherNotes
   * @return otherNotes
  **/
  @Schema(example = "More notes", description = "")
  public String getOtherNotes() {
    return otherNotes;
  }

  public void setOtherNotes(String otherNotes) {
    this.otherNotes = otherNotes;
  }

  public PutDataTablesAppTableIdDatatableIdRequest pointsScore(Long pointsScore) {
    this.pointsScore = pointsScore;
    return this;
  }

   /**
   * Get pointsScore
   * @return pointsScore
  **/
  @Schema(example = "20", description = "")
  public Long getPointsScore() {
    return pointsScore;
  }

  public void setPointsScore(Long pointsScore) {
    this.pointsScore = pointsScore;
  }

  public PutDataTablesAppTableIdDatatableIdRequest dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  @Schema(example = "dd MMMM yyyy", description = "")
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public PutDataTablesAppTableIdDatatableIdRequest locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @Schema(example = "en", description = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutDataTablesAppTableIdDatatableIdRequest putDataTablesAppTableIdDatatableIdRequest = (PutDataTablesAppTableIdDatatableIdRequest) o;
    return Objects.equals(this.dateOfBirth, putDataTablesAppTableIdDatatableIdRequest.dateOfBirth) &&
        Objects.equals(this.educationCdHighest, putDataTablesAppTableIdDatatableIdRequest.educationCdHighest) &&
        Objects.equals(this.name, putDataTablesAppTableIdDatatableIdRequest.name) &&
        Objects.equals(this.otherNotes, putDataTablesAppTableIdDatatableIdRequest.otherNotes) &&
        Objects.equals(this.pointsScore, putDataTablesAppTableIdDatatableIdRequest.pointsScore) &&
        Objects.equals(this.dateFormat, putDataTablesAppTableIdDatatableIdRequest.dateFormat) &&
        Objects.equals(this.locale, putDataTablesAppTableIdDatatableIdRequest.locale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateOfBirth, educationCdHighest, name, otherNotes, pointsScore, dateFormat, locale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutDataTablesAppTableIdDatatableIdRequest {\n");
    
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    educationCdHighest: ").append(toIndentedString(educationCdHighest)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    otherNotes: ").append(toIndentedString(otherNotes)).append("\n");
    sb.append("    pointsScore: ").append(toIndentedString(pointsScore)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
