/*
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.3.0-806-gcdf3c76-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.apache.fineract.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.apache.fineract.client.models.Image;
/**
 * Staff
 */


public class Staff {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("loanOfficer")
  private Boolean loanOfficer = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("image")
  private Image image = null;

  @SerializedName("notActive")
  private Boolean notActive = null;

  @SerializedName("notLoanOfficer")
  private Boolean notLoanOfficer = null;

  @SerializedName("new")
  private Boolean _new = null;

  public Staff id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Staff loanOfficer(Boolean loanOfficer) {
    this.loanOfficer = loanOfficer;
    return this;
  }

   /**
   * Get loanOfficer
   * @return loanOfficer
  **/
  @Schema(description = "")
  public Boolean isLoanOfficer() {
    return loanOfficer;
  }

  public void setLoanOfficer(Boolean loanOfficer) {
    this.loanOfficer = loanOfficer;
  }

  public Staff active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Staff image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(description = "")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public Staff notActive(Boolean notActive) {
    this.notActive = notActive;
    return this;
  }

   /**
   * Get notActive
   * @return notActive
  **/
  @Schema(description = "")
  public Boolean isNotActive() {
    return notActive;
  }

  public void setNotActive(Boolean notActive) {
    this.notActive = notActive;
  }

  public Staff notLoanOfficer(Boolean notLoanOfficer) {
    this.notLoanOfficer = notLoanOfficer;
    return this;
  }

   /**
   * Get notLoanOfficer
   * @return notLoanOfficer
  **/
  @Schema(description = "")
  public Boolean isNotLoanOfficer() {
    return notLoanOfficer;
  }

  public void setNotLoanOfficer(Boolean notLoanOfficer) {
    this.notLoanOfficer = notLoanOfficer;
  }

  public Staff _new(Boolean _new) {
    this._new = _new;
    return this;
  }

   /**
   * Get _new
   * @return _new
  **/
  @Schema(description = "")
  public Boolean isNew() {
    return _new;
  }

  public void setNew(Boolean _new) {
    this._new = _new;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Staff staff = (Staff) o;
    return Objects.equals(this.id, staff.id) &&
        Objects.equals(this.loanOfficer, staff.loanOfficer) &&
        Objects.equals(this.active, staff.active) &&
        Objects.equals(this.image, staff.image) &&
        Objects.equals(this.notActive, staff.notActive) &&
        Objects.equals(this.notLoanOfficer, staff.notLoanOfficer) &&
        Objects.equals(this._new, staff._new);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, loanOfficer, active, image, notActive, notLoanOfficer, _new);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Staff {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    loanOfficer: ").append(toIndentedString(loanOfficer)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    notActive: ").append(toIndentedString(notActive)).append("\n");
    sb.append("    notLoanOfficer: ").append(toIndentedString(notLoanOfficer)).append("\n");
    sb.append("    _new: ").append(toIndentedString(_new)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
